# Generated by Django 3.0 on 2020-08-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200801_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='real_name',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
