# Generated by Django 3.0 on 2020-08-02 09:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_real_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='real_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
